# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

orbs:
  orb-fsa: npm-plugin/orb-fsa@dev:test

jobs:
  test2:
    steps:
      - run: bash ls
workflows:
  test:
    jobs:
      - test2
      - orb-fsa/orb-fsa:
          api_key: "324234234"