# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

orbs:
  orb-fsa: npm-plugin/orb-fsa@dev:test

workflows:
  test:
    jobs:
      - orb-fsa/orb-fsa:
          api_key: "75d3b63c61254eb4a15e30332074ea7e23b33f000b384e44993d655e9a0a4a37"