# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

orbs:
  orb-fsa: npm-plugin/orb-fsa@dev:test

jobs:
 build:
   docker:
      - image: circleci/openjdk:8-jdk
   steps:
     - checkout
     - run:
         name: The First Step
         command: |
          pwd
     - run:
         name: Code Has Arrived
         command: |
           ls -al

workflows:
  test:
    jobs:
     - run:
         name: Code Has Arrived
         command: |
           ls -al
      - orb-fsa/orb-fsa:
          api_key: "324234234"
          directory: "/root/project"