# Java Maven CircleCI 2.1 configuration file
#

version: 2.1

orbs:
  orb-fsa: npm-plugin/orb-fsa@dev:test

workflows:
  test:
    jobs:
      - orb-fsa/orb-fsa:
          context: WhiteSource
          api_key: "22333"
          config_file_path: "https://s3.amazonaws.com/file-system-agent/SNAPSHOT/whitesource-fs-agent.config"